package packages;
// Generated 2016-12-29 11:01:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String accountid;
     private String username;
     private String password;
     private Integer age;
     private Date birthdate;
     private String email;
     private String country;
     private String phonenumber;
     public String temp_id;

    public Users() {
    }

	
    public Users(String accountid) {
        this.accountid = accountid;
    }
    public Users(String accountid, String username, String password, Integer age, Date birthdate, String email, String country, String phonenumber) {
       this.accountid = accountid;
       this.username = username;
       this.password = password;
       this.age = age;
       this.birthdate = birthdate;
       this.email = email;
       this.country = country;
       this.phonenumber = phonenumber;
    }
   
    public String getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * @return the temp_id
     */
    public String getTemp_id() {
        return temp_id;
    }

    /**
     * @param temp_id the temp_id to set
     */
    public void setTemp_id(String temp_id) {
        this.temp_id = temp_id;
    }




}


